package com.hrm.attendance.model;

import java.util.Date;
import java.util.UUID;

public class AttendanceLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private UUID id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.employee_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.check_time
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.type
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.latitude
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.longitude
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.device_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.network_ip
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private String networkIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.image_url
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.is_valid
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Boolean isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_logs.created_at
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.id
     *
     * @return the value of attendance_logs.id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public UUID getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.id
     *
     * @param id the value for attendance_logs.id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.employee_id
     *
     * @return the value of attendance_logs.employee_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.employee_id
     *
     * @param employeeId the value for attendance_logs.employee_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.check_time
     *
     * @return the value of attendance_logs.check_time
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.check_time
     *
     * @param checkTime the value for attendance_logs.check_time
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.type
     *
     * @return the value of attendance_logs.type
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.type
     *
     * @param type the value for attendance_logs.type
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.latitude
     *
     * @return the value of attendance_logs.latitude
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.latitude
     *
     * @param latitude the value for attendance_logs.latitude
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.longitude
     *
     * @return the value of attendance_logs.longitude
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.longitude
     *
     * @param longitude the value for attendance_logs.longitude
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.device_id
     *
     * @return the value of attendance_logs.device_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.device_id
     *
     * @param deviceId the value for attendance_logs.device_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.network_ip
     *
     * @return the value of attendance_logs.network_ip
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public String getNetworkIp() {
        return networkIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.network_ip
     *
     * @param networkIp the value for attendance_logs.network_ip
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setNetworkIp(String networkIp) {
        this.networkIp = networkIp == null ? null : networkIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.image_url
     *
     * @return the value of attendance_logs.image_url
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.image_url
     *
     * @param imageUrl the value for attendance_logs.image_url
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.is_valid
     *
     * @return the value of attendance_logs.is_valid
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.is_valid
     *
     * @param isValid the value for attendance_logs.is_valid
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_logs.created_at
     *
     * @return the value of attendance_logs.created_at
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_logs.created_at
     *
     * @param createdAt the value for attendance_logs.created_at
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}