package com.hrm.attendance.model;

import java.util.Date;
import java.util.UUID;

public class DailyTimesheet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_timesheets.id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private UUID id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_timesheets.employee_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_timesheets.date
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_timesheets.first_check_in
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date firstCheckIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_timesheets.last_check_out
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date lastCheckOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_timesheets.working_hours
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Double workingHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_timesheets.status
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_timesheets.shift_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Object shiftId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_timesheets.created_at
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_timesheets.updated_at
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_timesheets.id
     *
     * @return the value of daily_timesheets.id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public UUID getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_timesheets.id
     *
     * @param id the value for daily_timesheets.id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_timesheets.employee_id
     *
     * @return the value of daily_timesheets.employee_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_timesheets.employee_id
     *
     * @param employeeId the value for daily_timesheets.employee_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_timesheets.date
     *
     * @return the value of daily_timesheets.date
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_timesheets.date
     *
     * @param date the value for daily_timesheets.date
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_timesheets.first_check_in
     *
     * @return the value of daily_timesheets.first_check_in
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getFirstCheckIn() {
        return firstCheckIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_timesheets.first_check_in
     *
     * @param firstCheckIn the value for daily_timesheets.first_check_in
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setFirstCheckIn(Date firstCheckIn) {
        this.firstCheckIn = firstCheckIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_timesheets.last_check_out
     *
     * @return the value of daily_timesheets.last_check_out
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getLastCheckOut() {
        return lastCheckOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_timesheets.last_check_out
     *
     * @param lastCheckOut the value for daily_timesheets.last_check_out
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setLastCheckOut(Date lastCheckOut) {
        this.lastCheckOut = lastCheckOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_timesheets.working_hours
     *
     * @return the value of daily_timesheets.working_hours
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Double getWorkingHours() {
        return workingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_timesheets.working_hours
     *
     * @param workingHours the value for daily_timesheets.working_hours
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setWorkingHours(Double workingHours) {
        this.workingHours = workingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_timesheets.status
     *
     * @return the value of daily_timesheets.status
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_timesheets.status
     *
     * @param status the value for daily_timesheets.status
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_timesheets.shift_id
     *
     * @return the value of daily_timesheets.shift_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Object getShiftId() {
        return shiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_timesheets.shift_id
     *
     * @param shiftId the value for daily_timesheets.shift_id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setShiftId(Object shiftId) {
        this.shiftId = shiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_timesheets.created_at
     *
     * @return the value of daily_timesheets.created_at
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_timesheets.created_at
     *
     * @param createdAt the value for daily_timesheets.created_at
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_timesheets.updated_at
     *
     * @return the value of daily_timesheets.updated_at
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_timesheets.updated_at
     *
     * @param updatedAt the value for daily_timesheets.updated_at
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}