package com.hrm.attendance.model;

import java.util.Date;
import java.util.UUID;

public class Shift {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifts.id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private UUID id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifts.name
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifts.start_time
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifts.end_time
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifts.break_start
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date breakStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifts.break_end
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    private Date breakEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifts.id
     *
     * @return the value of shifts.id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public UUID getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifts.id
     *
     * @param id the value for shifts.id
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifts.name
     *
     * @return the value of shifts.name
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifts.name
     *
     * @param name the value for shifts.name
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifts.start_time
     *
     * @return the value of shifts.start_time
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifts.start_time
     *
     * @param startTime the value for shifts.start_time
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifts.end_time
     *
     * @return the value of shifts.end_time
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifts.end_time
     *
     * @param endTime the value for shifts.end_time
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifts.break_start
     *
     * @return the value of shifts.break_start
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getBreakStart() {
        return breakStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifts.break_start
     *
     * @param breakStart the value for shifts.break_start
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setBreakStart(Date breakStart) {
        this.breakStart = breakStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifts.break_end
     *
     * @return the value of shifts.break_end
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public Date getBreakEnd() {
        return breakEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifts.break_end
     *
     * @param breakEnd the value for shifts.break_end
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    public void setBreakEnd(Date breakEnd) {
        this.breakEnd = breakEnd;
    }
}