package com.hrm.attendance.mapper;

import com.hrm.attendance.model.AttendanceLog;
import java.util.List;
import java.util.UUID;

public interface AttendanceLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_logs
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_logs
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    int insert(AttendanceLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_logs
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    AttendanceLog selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_logs
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    List<AttendanceLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_logs
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    int updateByPrimaryKey(AttendanceLog row);
}