package com.hrm.attendance.mapper;

import com.hrm.attendance.model.DailyTimesheet;
import java.util.List;
import java.util.UUID;

public interface DailyTimesheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_timesheets
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_timesheets
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    int insert(DailyTimesheet row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_timesheets
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    DailyTimesheet selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_timesheets
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    List<DailyTimesheet> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_timesheets
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    int updateByPrimaryKey(DailyTimesheet row);
}