package com.hrm.attendance.mapper;

import com.hrm.attendance.model.Shift;
import java.util.List;
import java.util.UUID;

public interface ShiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shifts
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shifts
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    int insert(Shift row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shifts
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    Shift selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shifts
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    List<Shift> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shifts
     *
     * @mbg.generated Thu Nov 27 16:44:39 ICT 2025
     */
    int updateByPrimaryKey(Shift row);
}