package com.hrm.employee.mapper;

import com.hrm.employee.model.Department;
import java.util.List;
import java.util.UUID;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    int insert(Department row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    Department selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    int updateByPrimaryKey(Department row);
}