package com.hrm.auth.mapper;

import com.hrm.auth.model.UserRole;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Wed Nov 26 11:58:18 ICT 2025
     */
    int deleteByPrimaryKey(@Param("userId") Object userId, @Param("roleId") Object roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Wed Nov 26 11:58:18 ICT 2025
     */
    int insert(UserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Wed Nov 26 11:58:18 ICT 2025
     */
    List<UserRole> selectAll();
}