package com.hrm.auth.mapper;

import com.hrm.auth.model.User;
import java.util.List;
import java.util.UUID;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 26 11:58:18 ICT 2025
     */
    int deleteByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 26 11:58:18 ICT 2025
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 26 11:58:18 ICT 2025
     */
    User selectByPrimaryKey(UUID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 26 11:58:18 ICT 2025
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 26 11:58:18 ICT 2025
     */
    int updateByPrimaryKey(User row);
}