package com.hrm.employee.model;

import java.util.Date;
import java.util.UUID;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.id
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private UUID id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.name
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.code
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.created_at
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.id
     *
     * @return the value of departments.id
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public UUID getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.id
     *
     * @param id the value for departments.id
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.name
     *
     * @return the value of departments.name
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.name
     *
     * @param name the value for departments.name
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.code
     *
     * @return the value of departments.code
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.code
     *
     * @param code the value for departments.code
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.created_at
     *
     * @return the value of departments.created_at
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.created_at
     *
     * @param createdAt the value for departments.created_at
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}