package com.hrm.employee.model;

import java.util.Date;
import java.util.UUID;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.id
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private UUID id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.employee_code
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.full_name
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.email
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.phone_number
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.department_id
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private Object departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.job_title
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private String jobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.status
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.avatar_url
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.created_at
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.updated_at
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.id
     *
     * @return the value of employees.id
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public UUID getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.id
     *
     * @param id the value for employees.id
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.employee_code
     *
     * @return the value of employees.employee_code
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.employee_code
     *
     * @param employeeCode the value for employees.employee_code
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.full_name
     *
     * @return the value of employees.full_name
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.full_name
     *
     * @param fullName the value for employees.full_name
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.email
     *
     * @return the value of employees.email
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.email
     *
     * @param email the value for employees.email
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.phone_number
     *
     * @return the value of employees.phone_number
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.phone_number
     *
     * @param phoneNumber the value for employees.phone_number
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.department_id
     *
     * @return the value of employees.department_id
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public Object getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.department_id
     *
     * @param departmentId the value for employees.department_id
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setDepartmentId(Object departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.job_title
     *
     * @return the value of employees.job_title
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.job_title
     *
     * @param jobTitle the value for employees.job_title
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.status
     *
     * @return the value of employees.status
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.status
     *
     * @param status the value for employees.status
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.avatar_url
     *
     * @return the value of employees.avatar_url
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.avatar_url
     *
     * @param avatarUrl the value for employees.avatar_url
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.created_at
     *
     * @return the value of employees.created_at
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.created_at
     *
     * @param createdAt the value for employees.created_at
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.updated_at
     *
     * @return the value of employees.updated_at
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.updated_at
     *
     * @param updatedAt the value for employees.updated_at
     *
     * @mbg.generated Thu Nov 27 15:54:40 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}